Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	config.vm.define "cboutierS" do |cboutierS|
		cboutierS.vm.hostname = "cboutierS"
		cboutierS.vm.network "private_network",
			:ip => "192.168.42.110"
		cboutierS.vm.provider :libvirt do |libvirt|
			libvirt.cpus = 4
			libvirt.memory = 2048
			libvirt.management_network_name = 'vagrant-libvirt'
			libvirt.management_network_address = '192.168.42.2/24'
		end
		
		    config.vm.synced_folder "confs/", "/vagrant/confs", type: "rsync"

		cboutierS.vm.provision "install", type: "shell", path: "scripts/install-k3s-server.sh"
		cboutierS.vm.provision "deploy",  type: "shell", path: "scripts/deploy-apps.sh"
	end
end

