# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.box = "centos/8"
	config.vm.define "cboutierS" do |cboutierS|
		cboutierS.vm.hostname = "cboutierS"
		cboutierS.vm.network "private_network",
			:ip => "192.168.42.110"
		cboutierS.vm.provider :libvirt do |libvirt|
			libvirt.cpus = 1
			libvirt.memory = 512
			libvirt.management_network_name = 'vagrant-libvirt'
			libvirt.management_network_address = '192.168.42.2/24'
		end
		
		    config.vm.synced_folder "confs/", "/vagrant/confs", type: "rsync"

		cboutierS.vm.provision :shell, path: "scripts/master-node.sh", run: 'always'
	end
	config.vm.define "cboutierSW" do |cboutierSW|
		cboutierSW.vm.hostname = "cboutierSW"
		cboutierSW.vm.network "private_network",
			:ip => "192.168.42.111"
		cboutierSW.vm.provider :libvirt do |libvirt|
			libvirt.cpus = 1
			libvirt.memory = 512
			libvirt.management_network_name = 'vagrant-libvirt'
			libvirt.management_network_address = '192.168.42.2/24'
		end
		
		    config.vm.synced_folder "confs/", "/vagrant/confs", type: "rsync"


			cboutierSW.vm.provision :shell, path: "scripts/worker-node.sh", run: 'always'
	end
end

